### ISSUE TITLE
Mars Board Stuck at Starting Kernel.... 

### ISSUE THREAD

**Issue by sgnandish** [FrankBau/meta-marsboard-bsp#10]
Hi Frank,

I am using the Mars Board, For this board i build the "core-image-sato" image,For buliding this image i followed this link 
1) (https://github.com/FrankBau/meta-marsboard-bsp/wiki/Setting-up-the-Build-Environment),
2) Then i added QT5 layer to source dir (git clone -b jethro https://github.com/meta-qt5/meta-qt5.git)   3) Then i added the Mars Board layer to source dir (git clone -b krogoth https://github.com/FrankBau  
    /meta-marsboard-bsp)
4) Finally i set the "MACHINE=marsboard source setup-environment build" 
5) Then i build the image using "bitbake core-image-sato",
     in this case i am succeed to build and run the image on HDMI display without changing any uboot     
     parameter,
Now i am facing some problems they are as given below,
1) when i am recompile the "uImage" without changing anything in source i am getting the "uImage"                
     with only 2.1MB of size (but it was actually 5.8MB originally size), for compiling 
     in case (i) : "make -j4 uImage"  it gives 2.1MB size of uIamge. 
     in case (ii): "make -j4 uImage LOADADDR=0x10008000" it gives 5.0MB size of uImage. 
     when i am use the case (ii) uImage it is not working, and i set the load address also, it stuck at                     
     starting kernel....,   

2) Now i want to interface this board with "New Heaven Display 5" LCD [hx8257 driver IC]", so i  modified some changes in source then i recompile the "imx6q-marsboard.dts" and "uImage" for uImage i use the follwing command "make -j4 uImage LOADADDR=0x10008000" this also gives the same 5.0MB size of uImage, And i use this uImage with setting the Load Address it stuck at starting kernel...
  
below is the kernel logs:
=================================================================================
U-Boot 2016.09.01 (Feb 23 2017 - 11:55:26 +0530)

CPU:   Freescale i.MX6D rev1.2 996 MHz (running at 792 MHz)
CPU:   Extended Commercial temperature grade (-20C to 105C) at 39C
Reset cause: POR
Board: MarSBoard
I2C:   ready
DRAM:  1 GiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
SF: Detected SST25VF016B with page size 256 Bytes, erase size 4 KiB, total 2 MiB
No panel detected: default to HDMI
Display: HDMI (1024x768)
In:    serial
Out:   serial
Err:   serial
Net:   FEC [PRIME]
Error: FEC address not set.

Hit any key to stop autoboot:  0 
reading /uImage
4970760 bytes read in 259 ms (18.3 MiB/s)
reading /imx6q-marsboard.dtb
36549 bytes read in 19 ms (1.8 MiB/s)
## Booting kernel from Legacy Image at 10800000 ...
   Image Name:   Linux-4.1.15+
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    4970696 Bytes = 4.7 MiB
   Load Address: 10008000
   Entry Point:  10008000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 12000000
   Booting using the fdt blob at 0x12000000
   Loading Kernel Image ... OK
   Using Device Tree in place at 12000000, end 1200bec4

Starting kernel ...
=================================================================================
then i update the "u-boot.imx" also it doesn't help me to solve this issue,
 
could you please help me to come out this problem,   

Thanks in advance

Best Regards

nandishsg

**Comment by FrankBau** [comment]
Hi nandishsg,

no idea why your uImage gets so small. 
You can rebuild a modified kernel from a bitbake shell like
    `bitbake -f -c compile virtual/kernel`
which should work correctly.

Don't know your display, but I2C busses are already enabled in the default device tree. 
So you might start with an unmodified kernel and setting I2C from the command line (i2c-tools)
or user mode C code, see https://github.com/FrankBau/meta-marsboard-bsp/wiki/Using-I2C.
When your display works, you may shift the code later into a kernel module. Or, start with https://github.com/notro/fbtft/wiki/How-it-works ?

hth

Frank

**Comment by sgnandish** [comment]
Hi Frank 
 
 Thank You for your valuable reply,
 Dear frank i am facing the same issues again i.e " Starting Kernel.... " 
 After modifying the kernel i execute the command in bitbake shell  what you specified in previous post      
 i.e " bitbake -f -c compile virtual/kernel " but i am not seeing any change in the following directory     
 "/MARS/build/tmp/deploy/images/marsboard$ " ,
 So after that i recompile the "uImage" and "imx6q-marsboard.dts" with using the following commands 
 "make -j4 uImage LOADADDR=0x10008000"  and "make imx6q-marsboard.dtb" 
 Then the following u-boot parameter which i set:
setenv bootcmd "mmc rescan; fatload mmc 0:1 0x10008000 /uImage; fatload mmc 0:1 0x12000000 /imx6q-marsboard.dtb; bootm 0x10008000 - 0x12000000"  
below is the kernel boot logs:
============================================================================
U-Boot 2016.09.01 (Mar 01 2017 - 18:03:40 +0530)

CPU:   Freescale i.MX6D rev1.2 996 MHz (running at 792 MHz)
CPU:   Extended Commercial temperature grade (-20C to 105C) at 30C
Reset cause: WDOG
Board: MarSBoard
I2C:   ready
DRAM:  1 GiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
SF: Detected SST25VF016B with page size 256 Bytes, erase size 4 KiB, total 2 MiB
No panel detected: default to HDMI
Display: HDMI (1024x768)
In:    serial
Out:   serial
Err:   serial
Net:   FEC [PRIME]
Error: FEC address not set.

Hit any key to stop autoboot:  0 
reading /uImage
5327336 bytes read in 265 ms (19.2 MiB/s)
reading /imx6q-marsboard.dtb
36510 bytes read in 18 ms (1.9 MiB/s)
## Booting kernel from Legacy Image at 10008000 ...
   Image Name:   Linux-4.1.15+
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    5327272 Bytes = 5.1 MiB
   Load Address: 10008000
   Entry Point:  10008000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 12000000
   Booting using the fdt blob at 0x12000000
   Loading Kernel Image ... OK
   Using Device Tree in place at 12000000, end 1200be9d

Starting kernel ...
============================================================================
could you please tell me where i am wrong in this case, if you need any input from my side please let me know, 
Thanks in Advance 
Best Regards
Nandish sg

**Comment by sgnandish** [comment]
Hi Frank 
 
 Thank You for your valuable reply,
 Dear frank i am facing the same issues again i.e " Starting Kernel.... " 
 After modifying the kernel i execute the command in bitbake shell  what you specified in previous post      
 i.e " bitbake -f -c compile virtual/kernel " but i am not seeing any change in the following directory     
 "/MARS/build/tmp/deploy/images/marsboard$ " ,
 So after that i recompile the "uImage" and "imx6q-marsboard.dts" with using the following commands 
 "make -j4 uImage LOADADDR=0x10008000"  and "make imx6q-marsboard.dtb" 
 Then the following u-boot parameter which i set:
setenv bootcmd "mmc rescan; fatload mmc 0:1 0x10008000 /uImage; fatload mmc 0:1 0x12000000 /imx6q-marsboard.dtb; bootm 0x10008000 - 0x12000000"  
below is the kernel boot logs:
============================================================================
U-Boot 2016.09.01 (Mar 01 2017 - 18:03:40 +0530)

CPU:   Freescale i.MX6D rev1.2 996 MHz (running at 792 MHz)
CPU:   Extended Commercial temperature grade (-20C to 105C) at 30C
Reset cause: WDOG
Board: MarSBoard
I2C:   ready
DRAM:  1 GiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
SF: Detected SST25VF016B with page size 256 Bytes, erase size 4 KiB, total 2 MiB
No panel detected: default to HDMI
Display: HDMI (1024x768)
In:    serial
Out:   serial
Err:   serial
Net:   FEC [PRIME]
Error: FEC address not set.

Hit any key to stop autoboot:  0 
reading /uImage
5327336 bytes read in 265 ms (19.2 MiB/s)
reading /imx6q-marsboard.dtb
36510 bytes read in 18 ms (1.9 MiB/s)
## Booting kernel from Legacy Image at 10008000 ...
   Image Name:   Linux-4.1.15+
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    5327272 Bytes = 5.1 MiB
   Load Address: 10008000
   Entry Point:  10008000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 12000000
   Booting using the fdt blob at 0x12000000
   Loading Kernel Image ... OK
   Using Device Tree in place at 12000000, end 1200be9d

Starting kernel ...
============================================================================
could you please tell me where i am wrong in this case, if you need any input from my side please let me know, 
Thanks in Advance 
Best Regards
Nandish sg

**Comment by sgnandish** [comment]
Hi Frank,

Could you have any suggestion for my previous post, 

Thank in Advance 
Best Regards 
Nandish SG

**Comment by FrankBau** [comment]
Hi nandishsg,

I'm busy with other projects right now, but I try to give you more explanations:

Don't know exactly what you changed in the kernel but, for testing, 
I enabled support for the TSC2046 touch screen controller in the kernel 

    bitbake -c menuconfig virtual/kernel

    -> Device Drivers
      -> Input device support
        -> Touchscreens 
            <M> ADS7846/TSC2046/AD7873 and AD(S)7843 based touchscreens

Next, I did

    bitbake -f -c compile virtual/kernel 

which enforces re-execution of the compile task for the kernel. The kernel has its own build system which decides what to re-build. The build results stay within the working directory of the kernel. For me this is `${BUILDDIR}/tmp/work/marsboard-poky-linux-gnueabi/linux-marsboard/4.1.15-r0/build`

And, yes, a new uImage has been built:

    ls -l ${BUILDDIR}/tmp/work/marsboard-poky-linux-gnueabi/linux-marsboard/4.1.15-r0/build/arch/arm/boot/uImage 
    -rw-r--r-- 1 frank frank 5797432 Mär  7 17:14 ${BUILDDIR}/tmp/work/marsboard-poky-linux-gnueabi/linux-marsboard/4.1.15-r0/build/arch/arm/boot/uImage

which has a reasonable size. 
But, the deploy folder still contains the old uImage (because bitbake only did a compile). Check with

    ls -l ${BUILDDIR}/tmp/deploy/images/marsboard

In order to update this file too, execute:

    bitbake virtual/kernel

This time, bitbake detects that it needs to do more after compile and issues all necessary tasks like compile_kernelmodules, uboot_mkimage, ... see statistics in `${BUILDDIR}/tmp/buildstats`
and logs in `${BUILDDIR}/tmp/work/marsboard-poky-linux-gnueabi/linux-marsboard/4.1.15-r0/temp`

Last, I rebuild the image because the touchsreen driver is a loadable kernel module which is in the root file system:

     bitbake image-multimedia-full

This will build a couple of dependent packages and finally update the image in the deploy folder.

Hope this helps

Frank

**Comment by sgnandish** [comment]
Hi Frank,

Thank you for your suggestion. I will try today which you mentioned above steps,

Best regards 
Nandish S.G

**Comment by sgnandish** [comment]
Hi Frank Bau,

Thanks for your support, i am successfully resolved the above issue, 

Best Regards 
Nandish S.G

**Comment by sgnandish** [comment]
Dear Frank,

PFA, I want to enable the touch screen in my LCD (St7789s LCD driver IC)  and touch controller is is FT6306DMB with MARS imx6 dual cortex A9 Board, when i am connect the pin no 42 & 43 on board side for I2C communication i am not getting any signal on oscilloscope(please refer the image name by LCDPARALLELPORT.png), But when i am connect the pin no 3 & 5 on Expantion Port(J11) in Board side i am getting the some signal on oscilloscope with wrong address(please refer the image ExpantionPort.png ), i am expecting the 0x38 is the correct address, in boot log i am getting the message like" could not detect touch screen -19" could you please help me where i am wrong in this case , how to solve this issue


Best regards / Mit freundlichen Grüßen

MARQUARDT INDIA PVT. LTD.
TDS-PU

Nandish S G

Tel.: +91 (0)20 6673 2032
Mobile: +91 9538980711
mailto: nandish.gurulingappa@marquardt.de
http://www.marquardt.com<http://www.marquardt.com/>
