### ISSUE TITLE
I2C Communication is not happen with dedicated pins For Touch Screen 

### ISSUE THREAD

**Issue by sgnandish** [FrankBau/meta-marsboard-bsp#12]
Hi FrankBau ,
PFA,
I want to enable the touch screen in my LCD (St7789s LCD driver IC)  and touch controller is is FT6306DMB with MARS imx6 dual cortex A9 Board, when i am connect the pin no 42 & 43 on board side for I2C communication i am not getting any signal on oscilloscope(please refer the image name by LCDPARALLELPORT.png), But when i am connect the pin no 3 & 5 on Expantion Port(J11) in Board side i am getting the some signal on oscilloscope with wrong address(please refer the image ExpantionPort.png ), i am expecting the 0x38 is the correct address, in boot log i am getting the message like" could not detect touch screen -19" could you please help me where i am wrong in this case , how to solve this issue, 

Best Regards 
sgnandish

**Comment by FrankBau** [comment]
Hi sgnandish,

sorry, but I'm quite busy with other projects right now. 

Frank

**Comment by sgnandish** [comment]
Hi FrankBau,
its, ok now LCD Touch is working,

Best Regards 
nandish sg

**Comment by sgnandish** [comment]
Hi FrankBau,

Thanks for your reply, I want just small help from your side, I need to put my own user application on mars board can you please guide me how to do in this case,

Thanks in advance

Best Regards
Nandish sg
