### ISSUE TITLE
Kernel won't boot

### ISSUE THREAD

**Issue by ldnunes** [FrankBau/meta-marsboard-bsp#2]
Hi. I'm trying to build and boot an image for my MarS board. I was able to build the `core-image-minal` and `virtual/bootloader` using bitbake without any errors, and even deploy the bootloader on the board. 

However, I got stuck trying to boot the kernel:

```
U-Boot 2015.07-rc2 (Dec 14 2015 - 21:16:52 -0200)

CPU:   Freescale i.MX6D rev1.2 996 MHz (running at 792 MHz)
CPU:   Extended Commercial temperature grade (-20C to 105C) at 42C
Reset cause: POR
Board: MarSBoard
I2C:   ready
DRAM:  1 GiB
MMC:   FSL_SDHC: 0, FSL_SDHC: 1
SF: Detected SST25VF016B with page size 256 Bytes, erase size 4 KiB, total 2 MiB
auto-detected panel HDMI
Display: HDMI (1024x768)
In:    serial
Out:   serial
Err:   serial
Net:   FEC [PRIME]
Hit any key to stop autoboot:  0 
reading /uImage
4761896 bytes read in 265 ms (17.1 MiB/s)
reading /imx6q-marsboard.dtb
40601 bytes read in 19 ms (2 MiB/s)
## Booting kernel from Legacy Image at 10800000 ...
   Image Name:   Linux-3.10.53-1.1.0+yocto+gebb44
   Image Type:   ARM Linux Kernel Image (uncompressed)
   Data Size:    4761832 Bytes = 4.5 MiB
   Load Address: 10008000
   Entry Point:  10008000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 12000000
   Booting using the fdt blob at 0x12000000
   Loading Kernel Image ... OK
   Using Device Tree in place at 12000000, end 1200ce98

Starting kernel ...
```

The boot process just stops there. There is some LED activity on the board for a few seconds, but I don't know if it is related to the kernel booting but not outputting anything to the console.

I followed the wiki instructions to the letter, deleted the build dir and then tried again, but with no success. I'm out of ideas. Can you help me? Thanks!

**Comment by janhieber** [comment]
Maybe you have the wrong serial console in use. So you wont see anything but LED is blinking.

**Comment by ldnunes** [comment]
@janhieber Thanks for the reply.
That's what I thought. I think that for some reason the kernel is not outputting to the console, be it for misconfiguration on my part or perhaps there is something missing on the compilation.

My U-Boot environment variable `bootargs` is set as this:

```
console=ttymxc1,115200 root=/dev/mmcblk0p2 rootwait rw init=/sbin/init
```

I removed all the clutter (ethernet and video configs) to make it easier to pinpoint the problem.

If someone can help me find the problem I'll pay with lots of Internet points. :smile:

**Comment by FrankBau** [comment]
Hi Lucas,

when Linux boots, two LEDs start in a periodic heartbeat pattern. Do you see this ?

**Comment by ldnunes** [comment]
Hi @FrankBau,

When I power up the board two LEDs light up and stay always on, and a third blinks occasionally. Those three LEDs are side-by-side on the board.

Also, if I have the console cable connected a fourth LED near the Ethernet connector blinks each time there's a console activity, like when I type something or there is some output from the board.

**Comment by ldnunes** [comment]
Ops, a small correction: there are TWO LEDs for the debug console on the side of the Ethernet connector, one for input and other for output.

**Comment by FrankBau** [comment]
Okay. Just did a bitbake build core-image-minimal and ... my kernel doesn't boot either :-( Must look into it. Frank

**Comment by FrankBau** [comment]
Hi Lucas,

It seems to be a device tree regression issue
When I do 
...sources/meta-marsboard-bsp$ git checkout ba75c7e84819db5879057ac12fbb67b3910ceac3

and build the .dtb, Linux boots okay.

Will review the latest changes

Frank

**Comment by ldnunes** [comment]
@FrankBau OK, got it. I'll wait for the review.

**Comment by ldnunes** [comment]
Hey @FrankBau, using `git bisect` I was able to boot up to commit 659fc924. So it is possible that 7adf2abe caused something else to fail?

I'm a complete newbie to kernel development, so I can't be of much help there. :confused:

**Comment by FrankBau** [comment]
Commit af37a5a68f1605d9adbfbd10de36d4acfbfd9a05 fixes this.

**Comment by ldnunes** [comment]
Hey @janhieber, @FrankBau, sorry for not responding earlier.
Just to confirm that the fix worked for me. Thanks for the help!
