### ISSUE TITLE
Build fails on jethro branch

### ISSUE THREAD

**Issue by gesterdj** [FrankBau/meta-marsboard-bsp#4]
Build target: core-image-base
Offending package: fsl-alsa-plugins
Compile error: 
/mnt/dat/Work/dev/ARM/iMX/jethro/build/tmp/work/marsboard-poky-linux-gnueabi/fsl-alsa-plugins/1.0.25-r0/fsl-alsa-plugins-1.0.25/asrc/asrc_pair.c:28:28: fatal error: linux/mxc_asrc.h: No such file or directory
compilation terminated.

**Comment by gesterdj** [comment]
Comment from http://permalink.gmane.org/gmane.linux.embedded.yocto.meta-freescale/4856

> fslc kernel doesn't provide these headers so most Freescale specific
> userland needing Freescale's kernel headers won't compile when you
> select fscl kernel.

Comment from http://permalink.gmane.org/gmane.linux.embedded.yocto.meta-freescale/13560

> Btw, mainline kernels have support only for the imx framebuffer, but no
> additional acceleration (VPU, GL, probably ASRC also). All these extras
> are available only with the vendor's kernel.
> 
> If you need the acceleration, I would suggest going back to 3.14.28.

http://permalink.gmane.org/gmane.linux.embedded.yocto.meta-freescale/4855 recommends

> or add MACHINE_EXTRA_RRECOMMENDS_remove = "imx-audio fsl-alsa-plugins"
> in your local.conf

**Comment by FrankBau** [comment]
switched to boundary-imx 3.14 kernel which supports alsa and hardware acceleration
