### ISSUE TITLE
recipe image-multimedia-full fails on branch jethro

### ISSUE THREAD

**Issue by gesterdj** [FrankBau/meta-marsboard-bsp#5]
ERROR: Nothing RPROVIDES 'packagegroup-fslc-gstreamer1.0' (but /jethro/sources/meta-marsboard-bsp/recipes-images/image-multimedia-full/image-multimedia-full.bb RDEPENDS on or otherwise requires it)

**Comment by gesterdj** [comment]
Seems to be a typo
`diff --git a/recipes-images/image-multimedia-full/image-multimedia-full.bb b/recipes-images/image-multimedia-full/image-multimedia-full.bb`
`index 294bbb8..77dfb3e 100644`
`--- a/recipes-images/image-multimedia-full/image-multimedia-full.bb`
`+++ b/recipes-images/image-multimedia-full/image-multimedia-full.bb`
`@@ -9,8 +9,8 @@ EXTRA_IMAGE_FEATURES += " tools-testapps tools-profile"`
`IMAGE_INSTALL_append += " htop i2c-tools"`
` `
`IMAGE_INSTALL_append += " `
`-    packagegroup-fslc-gstreamer1.0 \`
`-    packagegroup-fslc-gstreamer1.0-full \`
`+    packagegroup-fsl-gstreamer1.0 \`
`+    packagegroup-fsl-gstreamer1.0-full \`
`packagegroup-fsl-tools-gpu \`
`packagegroup-fsl-tools-gpu-external \`
`packagegroup-fsl-tools-testapps \`

**Comment by FrankBau** [comment]
Thanks, I will fix this.
