### ISSUE TITLE
recipe image-multimedia-full fails on branch jethro

### ISSUE THREAD

**Issue by aturowski** [FrankBau/meta-marsboard-bsp#7]
Doing
bitbake image-multimedia-full
fails while linking eglingo-fb_1.0.0.bb recipe and gives following errors

[snip]
undefined reference to `fbCreateWindow'
[snip]
undefined reference to`fbGetDisplayByIndex'
[snip]
collect2: error: ld returned 1 exis status
[snip]
sources/poky/meta/recipes-graphics/eglinfo-fb_1.0.0.bb do_compile failed with exit code 1

Removing "eglinfo-fb" from IMAGE_INSTALL_append in sources/meta-marsboard-bsp/recipes-images/image-multimedia-full/image-multimedia-full.bb works around this linking error as ellinfo-fb is not built at all. Found https://www.toradex.com/community/questions/2477/how-to-add-framebuffer-egl-to-console-trdx-image.html

**Comment by FrankBau** [comment]
This is because I usually build with framebuffer (DISTRO_FEATURES_remove = "x11 wayland" in local.conf). I made the append conditional in the new krogoth branch.
hth
Frank
