### ISSUE TITLE
devregs in C language

### ISSUE THREAD

**Issue by mau-tux** [FrankBau/meta-marsboard-bsp#8]
Hi,
as many boards (like mine) doesn't have C++ libraries installed by default, I made some little adaptations to devregs.cpp to convert it in C language.

I put converted file here to anyone needs a C binary instead of C++ one.

This binary is based on devregs.cpp in commit fdd9c392f5273d26696315939e0ab893e4cbc6cb.

To compile it using included autoconf, simply place attached .c file in src directory and apply below changes:

diff --git a/configure.ac b/configure.ac
index 374e12b..e8dc528 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1,9 +1,9 @@
 dnl Process this file with autoconf to produce a configure script.
 AC_INIT(devregs, 1.0, info@boundarydevices.com)
-AC_CONFIG_SRCDIR(src/devregs.cpp)
+AC_CONFIG_SRCDIR(src/devregs.c)
 
 AM_INIT_AUTOMAKE
 
-AC_PROG_CXX
+AC_PROG_CC
 
 AC_OUTPUT(Makefile src/Makefile)
diff --git a/src/Makefile.am b/src/Makefile.am
index 22f3556..faf2fc7 100644
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -1,4 +1,4 @@
 bin_PROGRAMS = devregs
-devregs_SOURCES = devregs.cpp
+devregs_SOURCES = devregs.c
 
 sysconf_DATA = $(top_srcdir)/dat/*.dat

Note that I only made simple changes to translate it to C, I didn't do/add anything other (like check of return value of mallocs, free allocated space etc.).

Regards

mauro

[devregs.c.txt](https://github.com/FrankBau/meta-marsboard-bsp/files/642177/devregs.c.txt)

**Comment by FrankBau** [comment]
Hi mau-tux,
thanks for your contribution and sorry for the delayed answer. 
devregs belongs to another repo, not mine: https://github.com/boundarydevices/meta-boundary/tree/morty/recipes-boundary. 
Frank

**Comment by mau-tux** [comment]
Hi Frank,
oh sorry, I will submit these changes to them.

regards
Mauro
